# Olist Data Cleaning

## Imported pandas and os

In [1]:
import pandas as pd

In [2]:
import os

<hr>

## Importing Orders Data from CSV to Dataframe

In [3]:
customers = pd.read_csv('olist_customers_dataset.csv')

In [4]:
geolocations = pd.read_csv('olist_geolocation_dataset.csv')

In [5]:
order_items = pd.read_csv('olist_order_items_dataset.csv')

In [6]:
payments = pd.read_csv('olist_order_payments_dataset.csv')

In [7]:
reviews = pd.read_csv('olist_order_reviews_dataset.csv')

In [8]:
orders = pd.read_csv('olist_orders_dataset.csv')

In [9]:
products = pd.read_csv('olist_products_dataset.csv')

In [10]:
sellers = pd.read_csv('olist_sellers_dataset.csv')

<hr>

### Finding which datasets have nulls

In [11]:
print(customers.isnull().sum())

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [12]:
print(geolocations.isnull().sum())

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [13]:
print(order_items.isnull().sum())

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [14]:
print(payments.isnull().sum())

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [15]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [16]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [17]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [18]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

#### Reviews, Orders and Products datasets have nulls.
<hr>

## CLean the Data

### Reviews

In [19]:
reviews['review_comment_title'] = reviews['review_comment_title'].fillna('No Title')

In [20]:
reviews['review_comment_message'] = reviews['review_comment_message'].fillna('No Comment')

In [21]:
reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

#### Filled nulls with 'No Title' and 'No Comment' for reviews
<hr>

### Orders

In [22]:
orders.loc[orders.isnull().any(axis = 1)].describe()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,2980,2980,2980,2980,2820,1197,15,2980
unique,2980,2980,8,2977,2807,1191,15,424
top,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,shipped,2017-07-07 21:17:36,2018-05-20 19:10:36,2018-01-26 20:12:58,2017-03-01 13:25:33,2018-02-06 00:00:00
freq,1,1,1107,2,2,2,1,20

#### there are about 3000 rows with nulls among the 100000 total rows.<br>

In [23]:
orders.loc[orders.isnull().any(axis = 1)]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaN,2018-06-28 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaN,2018-02-07 00:00:00
...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaN,NaN,NaN,2018-10-01 00:00:00
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaN,NaN,2018-02-06 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaN,NaN,NaN,2018-09-27 00:00:00
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaN,NaN,2017-09-15 00:00:00
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00

#### Orders purchased dates with nulls in approved, delivered dates that are not recent (within 3 months from latest date) present and should be dropped to not skew the data.
<hr>

### Finding latest order date and cutoff date

In [24]:
# changed data type of order_purchase timestamp to datetime to find max date and cutoff date
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])

In [25]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                        object
order_delivered_carrier_date             object
order_delivered_customer_date            object
order_estimated_delivery_date            object
dtype: object

In [26]:
max_date = orders['order_purchase_timestamp'].max()

In [27]:
max_date

Timestamp('2018-10-17 17:30:18')

In [28]:
cutoff_date = max_date - pd.DateOffset(months = 3)

In [29]:
cutoff_date

Timestamp('2018-07-17 17:30:18')

In [30]:
rows_to_drop = (orders['order_delivered_customer_date'].isnull() & (orders['order_purchase_timestamp'] < cutoff_date))

clean_orders = orders[~rows_to_drop]

In [31]:
clean_orders.isnull().sum()

order_id                           0
customer_id                        0
order_status                       0
order_purchase_timestamp           0
order_approved_at                 87
order_delivered_carrier_date     178
order_delivered_customer_date    256
order_estimated_delivery_date      0
dtype: int64

#### Orders which are not delivered or those with no records before 3 months from latest date were dropped.
<hr>

### Products

In [32]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [33]:
products_NAs = products.loc[products.isnull().any(axis = 1)]

In [34]:
products_NAs

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

#### Although product weight and dimensions exist, there were no descriptions. This could indicate faulty records or items not fully cataloged. We need to ensure descriptions are provided by vendors or consider removing such incomplete records if they negatively impact analysis or operations. However for the sake of the project constraints, these products will be dropped for now along with products without dimensions and weight data.

In [35]:
rows_to_drop = (products['product_category_name'].isnull() & products['product_name_lenght'].isnull() &
                products['product_description_lenght'].isnull() & products['product_photos_qty'].isnull())

clean_products = products[~rows_to_drop]

In [37]:
clean_products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              1
product_length_cm             1
product_height_cm             1
product_width_cm              1
dtype: int64

In [38]:
# the only product with null product dimensions(height, length, width) is dropped
clean_products = clean_products[~(clean_products['product_weight_g'].isnull())]

In [39]:
clean_products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

## <hr> Exporting Cleaned Data to be put into Power Bi for dashboard creation and visual analysis

#### Saving the cleaned data to CSV

In [40]:
#export without a new index column added
reviews.to_csv('clean_reviews.csv', index=False)
clean_orders.to_csv('clean_orders.csv', index=False)
clean_products.to_csv('clean_proeucts.csv', index=False)